-- Expand the institutional archive so it can hold every platform output.
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'FINANCIAL_STATEMENT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'DECISION';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'POLICY';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'CONTRACT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'RESEARCH';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'MANUAL';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'TOOLKIT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'LESSON_LEARNED';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'BEST_PRACTICE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PRESENTATION';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'CORRESPONDENCE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'MEDIA';

ALTER TABLE "documents"
  ALTER COLUMN "fileUrl" DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS "content" TEXT,
  ADD COLUMN IF NOT EXISTS "source" VARCHAR(50) NOT NULL DEFAULT 'PLATFORM_OUTPUT',
  ADD COLUMN IF NOT EXISTS "sourceId" VARCHAR(100);

CREATE INDEX IF NOT EXISTS "documents_source_idx" ON "documents"("source");
CREATE UNIQUE INDEX IF NOT EXISTS "documents_source_sourceId_key" ON "documents"("source", "sourceId");
